# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jacobmogline.dk" # the base hostname & protocol for your site
mapsApiKey: "AIzaSyDmz_QxarquPBZ5r7KBjwV7E10uUBCckh4"
# Build settings
markdown: kramdown
